default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  port: 5432
  user: kitty
  password: kitty
  url: <%= ENV.fetch('DATABASE_URL', '') + '_development' %>
  #database: kitty_development

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') + '_test' %>
